{"name":"test_resubmit_refund_journey","id":"uk.gov.hmcts.reform.refunds.RefundsApproverJourneyFunctionalTest:test_resubmit_refund_journey","testCaseName":"uk.gov.hmcts.reform.refunds.RefundsApproverJourneyFunctionalTest","userStory":{"id":"uk.gov.hmcts.reform.refunds.RefundsApproverJourneyFunctionalTest","storyName":"Refunds approver journey functional test","storyClassName":"uk.gov.hmcts.reform.refunds.RefundsApproverJourneyFunctionalTest","path":"uk.gov.hmcts.reform.refunds","type":"story"},"featureTag":{"name":"Refunds/Refunds approver journey functional test","type":"story","displayName":"Refunds/Refunds approver journey functional test"},"title":"Test resubmit refund journey","tags":[{"name":"Refunds/Refunds approver journey functional test","type":"story","displayName":"Refunds/Refunds approver journey functional test"}],"startTime":"2021-09-27T15:39:46.012461+01:00[Europe/London]","duration":5806,"testFailureCause":{"errorType":"org.opentest4j.AssertionFailedError","message":"\nexpected: 1\n but was: 4","stackTrace":[{"classLoaderName":"app","declaringClass":"uk.gov.hmcts.reform.refunds.RefundsApproverJourneyFunctionalTest","methodName":"test_resubmit_refund_journey","fileName":"RefundsApproverJourneyFunctionalTest.java","lineNumber":348,"format":1},{"classLoaderName":"app","declaringClass":"org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks","methodName":"evaluate","fileName":"RunBeforeTestMethodCallbacks.java","lineNumber":75,"format":1},{"classLoaderName":"app","declaringClass":"org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks","methodName":"evaluate","fileName":"RunAfterTestMethodCallbacks.java","lineNumber":86,"format":1},{"classLoaderName":"app","declaringClass":"org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks","methodName":"evaluate","fileName":"RunBeforeTestClassCallbacks.java","lineNumber":61,"format":1},{"classLoaderName":"app","declaringClass":"org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks","methodName":"evaluate","fileName":"RunAfterTestClassCallbacks.java","lineNumber":70,"format":1}]},"testFailureClassname":"org.opentest4j.AssertionFailedError","testFailureMessage":"\nexpected: 1\n but was: 4","testFailureSummary":"FAILURE;org.opentest4j.AssertionFailedError;\nexpected: 1\n but was: 4;RefundsApproverJourneyFunctionalTest.java","projectKey":"","annotatedResult":"FAILURE","isManualTestingUpToDate":false,"manual":false,"testSource":"JUnit","order":0,"result":"FAILURE"}